PROJECT_SOURCE_DIR := $(abspath ./)
CMAKE_BUILD_TYPE ?= Debug
BUILD_DIR ?= $(PROJECT_SOURCE_DIR)/build
NUM_JOB ?= 12
CMAKE_ARGS := \
	-DCMAKE_BUILD_TYPE=$(CMAKE_BUILD_TYPE) \
	-DCMAKE_INSTALL_PREFIX=$(INSTALL_DIR) \
	-DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_CXX_FLAGS=-fPIC -DCMAKE_C_FLAGS=-fPIC \
	-DEXTERNAL_ZHTSDK=$(EXTERNAL_ZHTSDK) \

.PHONY: FORCE
FORCE:

build: FORCE
	mkdir -p $(BUILD_DIR) && cd $(BUILD_DIR) && \
	cmake $(PROJECT_SOURCE_DIR) $(CMAKE_ARGS) && \
	make -j$(NUM_JOB) \
	# make install

clean: FORCE
	rm -rf build


